# Generated by Django 4.2.4 on 2023-08-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_alter_teacher_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
