# Generated by Django 4.2.4 on 2023-08-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_alter_teacher_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
