# Generated by Django 4.2.4 on 2023-08-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('textId', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('firstName', models.CharField(max_length=150)),
                ('lastName', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('BD', 'Bangladesh'), ('IND', 'India'), ('PAK', 'Pakistan'), ('US', 'United States'), ('QTR', 'Qatar')], default='BD', max_length=20)),
                ('password', models.CharField(max_length=150)),
                ('otpCode', models.CharField(blank=True, max_length=6, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'EndUser',
            },
        ),
    ]
